const mongoose = require('mongoose');

const internacaoRegistroSchema = new mongoose.Schema(
  {
    codigo: { type: Number, required: true, unique: true, index: true },
    petId: { type: String, trim: true },
    petNome: { type: String, required: true, trim: true },
    petEspecie: { type: String, trim: true },
    petRaca: { type: String, trim: true },
    petPeso: { type: String, trim: true },
    petPesoAtualizadoEm: { type: Date },
    petIdade: { type: String, trim: true },
    tutorNome: { type: String, trim: true },
    tutorDocumento: { type: String, trim: true },
    tutorContato: { type: String, trim: true },
    situacao: { type: String, trim: true },
    situacaoCodigo: { type: String, trim: true },
    risco: { type: String, trim: true },
    riscoCodigo: { type: String, trim: true },
    veterinario: { type: String, trim: true },
    box: { type: String, trim: true },
    altaPrevistaData: { type: String, trim: true },
    altaPrevistaHora: { type: String, trim: true },
    queixa: { type: String, trim: true },
    diagnostico: { type: String, trim: true },
    prognostico: { type: String, trim: true },
    alergias: [{ type: String, trim: true }],
    acessorios: { type: String, trim: true },
    observacoes: { type: String, trim: true },
    execucoes: [
      {
        programadoData: { type: String, trim: true },
        programadoHora: { type: String, trim: true },
        programadoEm: { type: String, trim: true },
        horario: { type: String, trim: true },
        descricao: { type: String, trim: true },
        responsavel: { type: String, trim: true },
        status: { type: String, trim: true },
        prescricaoId: { type: String, trim: true },
        realizadoData: { type: String, trim: true },
        realizadoHora: { type: String, trim: true },
        realizadoEm: { type: String, trim: true },
        realizadoPor: { type: String, trim: true },
        observacoes: { type: String, trim: true },
      },
    ],
    prescricoes: [
      {
        tipo: { type: String, trim: true },
        frequencia: { type: String, trim: true },
        descricao: { type: String, trim: true },
        resumo: { type: String, trim: true },
        aCadaValor: { type: String, trim: true },
        aCadaUnidade: { type: String, trim: true },
        porValor: { type: String, trim: true },
        porUnidade: { type: String, trim: true },
        dataInicio: { type: String, trim: true },
        horaInicio: { type: String, trim: true },
        medUnidade: { type: String, trim: true },
        medDose: { type: String, trim: true },
        medVia: { type: String, trim: true },
        medPeso: { type: String, trim: true },
        medPesoAtualizadoEm: { type: String, trim: true },
        fluidFluido: { type: String, trim: true },
        fluidEquipo: { type: String, trim: true },
        fluidUnidade: { type: String, trim: true },
        fluidDose: { type: String, trim: true },
        fluidVia: { type: String, trim: true },
        fluidVelocidadeValor: { type: String, trim: true },
        fluidVelocidadeUnidade: { type: String, trim: true },
        fluidSuplemento: { type: String, trim: true },
        criadoPor: { type: String, trim: true },
        criadoEm: { type: Date, default: Date.now },
      },
    ],
    relatoriosMedicos: [
      {
        resumo: { type: String, trim: true },
        descricao: { type: String, trim: true },
        criadoPor: { type: String, trim: true },
        criadoEm: { type: Date, default: Date.now },
      },
    ],
    historico: [
      {
        tipo: { type: String, trim: true },
        descricao: { type: String, trim: true },
        criadoPor: { type: String, trim: true },
        criadoEm: { type: Date, default: Date.now },
      },
    ],
    altaRegistrada: { type: Boolean, default: false },
    altaVeterinario: { type: String, trim: true },
    altaData: { type: String, trim: true },
    altaHora: { type: String, trim: true },
    altaRelatorio: { type: String, trim: true },
    altaConfirmadaEm: { type: Date },
    cancelado: { type: Boolean, default: false },
    canceladoResponsavel: { type: String, trim: true },
    canceladoData: { type: String, trim: true },
    canceladoHora: { type: String, trim: true },
    canceladoJustificativa: { type: String, trim: true },
    canceladoObservacoes: { type: String, trim: true },
    canceladoRegistradoEm: { type: Date },
    obitoRegistrado: { type: Boolean, default: false },
    obitoVeterinario: { type: String, trim: true },
    obitoData: { type: String, trim: true },
    obitoHora: { type: String, trim: true },
    obitoCausa: { type: String, trim: true },
    obitoRelatorio: { type: String, trim: true },
    obitoConfirmadoEm: { type: Date },
  },
  {
    timestamps: true,
  },
);

module.exports = mongoose.model('InternacaoRegistro', internacaoRegistroSchema);
