export const internacaoDataset = {
  unidade: 'Hospital Veterinário E o Bicho',
  agendaReferencia: {
    dataISO: '2024-03-13',
    loja: 'Loja Clínica Jardim Paulista',
    texto: 'Dados sincronizados com a agenda de serviços (Banho & Tosa + Vet) de 13/03/2024',
    fichaAtualizada: 'Última ficha clínica salva às 11h45',
  },
  pacientes: [
    {
      id: 'pet-thor',
      nome: 'Thor',
      especie: 'Canino',
      raca: 'Border Collie',
      sexo: 'Macho',
      idade: '4 anos',
      peso: '18,4 kg',
      tutor: {
        nome: 'Ana Lima',
        documento: '***.123.788-10',
        telefone: '(11) 99888-5566',
        email: 'ana.lima@email.com',
      },
      agenda: {
        servico: 'Internação pós-operatória',
        origem: 'Agendado em 13/03 às 08h com Dra. Helena Costa',
      },
      internacao: {
        admissao: '2024-03-13T08:20:00',
        previsaoAlta: '2024-03-18T10:00:00',
        motivo: 'Correção de ruptura de ligamento cruzado',
        status: 'Em observação',
        box: 'Box 03',
        equipeMedica: 'Dra. Helena Costa',
        equipeEnfermagem: 'Enfª Camila Paes',
        pendencias: [
          'Aguardar laudo do hemograma solicitado na agenda às 07h45',
          'Reavaliar analgesia após fisioterapia da tarde',
        ],
        execucoes: [
          { horario: '08:30', descricao: 'Avaliação pós-operatória + SSVV', responsavel: 'Dra. Helena', status: 'Concluída' },
          { horario: '09:00', descricao: 'Analgesia - Tramadol 2mg/kg VO', responsavel: 'Enf. Camila', status: 'Concluída' },
          { horario: '11:30', descricao: 'Curativo e checagem de dreno', responsavel: 'Enf. Camila', status: 'Em execução' },
          { horario: '14:00', descricao: 'Fisioterapia passiva + crioterapia', responsavel: 'Fisio Marcos', status: 'Agendado' },
        ],
        historico: [
          { periodo: 'Jan/2024', motivo: 'Gastroenterite aguda', resultado: 'Alta em 48h com dieta prescrita', responsavel: 'Dr. Pedro Azevedo' },
          { periodo: 'Set/2023', motivo: 'Check-up pré-cirúrgico', resultado: 'Sem internação', responsavel: 'Dra. Helena Costa' },
        ],
        parametros: [
          { coleta: '13/03 08:25', temp: '38,4 ºC', fc: '92 bpm', fr: '28 mrm', pam: '110x70 mmHg', dor: '2/5', observacao: 'Levemente sonolento' },
          { coleta: '13/03 10:50', temp: '38,1 ºC', fc: '88 bpm', fr: '24 mrm', pam: '114x72 mmHg', dor: '1/5', observacao: 'Aceitou alimentação pastosa' },
        ],
        prescricoes: [
          { nome: 'Protocolo pós-operatório ortopédico', periodo: '5 dias', frequencia: '12/12h', itens: 'Cefalexina 30mg/kg + Meloxicam 0,1mg/kg', responsavel: 'Dra. Helena Costa' },
          { nome: 'Cuidados com dreno', periodo: '3 dias', frequencia: '6/6h', itens: 'Higienização com Clorexidina + curativo compressivo', responsavel: 'Enfª Camila Paes' },
        ],
      },
    },
    {
      id: 'pet-amora',
      nome: 'Amora',
      especie: 'Felina',
      raca: 'SRD (preta)',
      sexo: 'Fêmea',
      idade: '2 anos',
      peso: '3,2 kg',
      tutor: {
        nome: 'Rafael Campos',
        documento: '***.551.024-81',
        telefone: '(11) 94472-2099',
        email: 'rafael.campos@email.com',
      },
      agenda: {
        servico: 'Internação com isolamento respiratório',
        origem: 'Encaminhado da agenda de vacinação em 13/03 às 09h',
      },
      internacao: {
        admissao: '2024-03-13T09:35:00',
        previsaoAlta: '2024-03-16T08:00:00',
        motivo: 'Brônquio-pneumonia felina',
        status: 'Isolamento respiratório',
        box: 'Box 05',
        equipeMedica: 'Dr. Eduardo Sato',
        equipeEnfermagem: 'Téc. Laura Nunes',
        pendencias: [
          'Monitorar saturação a cada 4h',
          'Ajustar nebulização conforme escore respiratório',
        ],
        execucoes: [
          { horario: '09:50', descricao: 'Instalação de cateter e coleta de sangue', responsavel: 'Téc. Laura', status: 'Concluída' },
          { horario: '10:15', descricao: 'Nebulização com soro + brometo', responsavel: 'Téc. Laura', status: 'Concluída' },
          { horario: '12:30', descricao: 'Antibiótico - Doxiciclina 5mg/kg', responsavel: 'Dr. Eduardo', status: 'Em execução' },
          { horario: '16:00', descricao: 'Reavaliação respiratória + Raio-X', responsavel: 'Dr. Eduardo', status: 'Agendado' },
        ],
        historico: [
          { periodo: 'Out/2023', motivo: 'Episódio de rinotraqueíte', resultado: 'Tratamento domiciliar, sem internação', responsavel: 'Dr. Eduardo Sato' },
        ],
        parametros: [
          { coleta: '13/03 09:40', temp: '39,3 ºC', fc: '160 bpm', fr: '42 mrm', pam: '120/85 mmHg', dor: '3/5', observacao: 'Taquipneia leve' },
          { coleta: '13/03 12:20', temp: '38,9 ºC', fc: '150 bpm', fr: '32 mrm', pam: '118/80 mmHg', dor: '2/5', observacao: 'Melhora após nebulização' },
        ],
        prescricoes: [
          { nome: 'Plano respiratório intensivo', periodo: '72 horas', frequencia: '4/4h', itens: 'Nebulização + Clenil + Soro fisiológico', responsavel: 'Dr. Eduardo Sato' },
          { nome: 'Suporte nutricional felino', periodo: 'Durante a internação', frequencia: '6/6h', itens: 'Dieta pastosa hiperproteica + suplementação de taurina', responsavel: 'Nutri. Denise Prado' },
        ],
      },
    },
    {
      id: 'pet-bento',
      nome: 'Bento',
      especie: 'Canino',
      raca: 'Shih-tzu',
      sexo: 'Macho',
      idade: '8 anos',
      peso: '7,1 kg',
      tutor: {
        nome: 'Juliana Souza',
        documento: '***.882.214-09',
        telefone: '(11) 91224-6671',
        email: 'juliana.souza@email.com',
      },
      agenda: {
        servico: 'Internação curta para controle glicêmico',
        origem: 'Solicitado na ficha clínica após retorno de banho & tosa',
      },
      internacao: {
        admissao: '2024-03-12T18:10:00',
        previsaoAlta: '2024-03-14T11:00:00',
        motivo: 'Descompensação diabética',
        status: 'Estável',
        box: 'Box 01',
        equipeMedica: 'Dra. Marina Prado',
        equipeEnfermagem: 'Téc. Bruno Almeida',
        pendencias: [
          'Reajustar dose de insulina NPH às 18h',
          'Registrar curva glicêmica no prontuário compartilhado',
        ],
        execucoes: [
          { horario: '06:00', descricao: 'Coleta de glicemia capilar', responsavel: 'Téc. Bruno', status: 'Concluída' },
          { horario: '06:15', descricao: 'Administração de insulina 0,7UI/kg', responsavel: 'Dra. Marina', status: 'Concluída' },
          { horario: '10:00', descricao: 'Glicemia pós-prandial', responsavel: 'Téc. Bruno', status: 'Agendado' },
          { horario: '10:15', descricao: 'Avaliação médica + plano de alta', responsavel: 'Dra. Marina', status: 'Agendado' },
        ],
        historico: [
          { periodo: 'Ago/2022', motivo: 'Pancreatite aguda', resultado: 'Internação de 3 dias', responsavel: 'Dra. Marina Prado' },
          { periodo: 'Mai/2021', motivo: 'Controle de glicemia', resultado: 'Alta no mesmo dia', responsavel: 'Dr. Pedro Azevedo' },
        ],
        parametros: [
          { coleta: '13/03 06:05', temp: '38,0 ºC', fc: '96 bpm', fr: '18 mrm', pam: '108/68 mmHg', dor: '1/5', observacao: 'Sem sinais de dor' },
          { coleta: '13/03 08:40', temp: '38,2 ºC', fc: '100 bpm', fr: '20 mrm', pam: '110/70 mmHg', dor: '1/5', observacao: 'Glicemia 220 mg/dL' },
        ],
        prescricoes: [
          { nome: 'Curva glicêmica 24h', periodo: '24 horas', frequencia: '2/2h', itens: 'Glicemia capilar + registro no gráfico compartilhado', responsavel: 'Téc. Bruno Almeida' },
          { nome: 'Plano alimentar hipoglicídico', periodo: 'Durante a internação', frequencia: '8/8h', itens: 'Ração diabética + fracionamento de 3 porções', responsavel: 'Nutri. Denise Prado' },
        ],
      },
    },
  ],
  boxes: [
    { box: 'Box 01', ocupante: 'Bento', status: 'Estável', especialidade: 'Clínico', higienizacao: '07h40', observacao: 'Curva glicêmica em andamento' },
    { box: 'Box 02', ocupante: 'Livre', status: 'Disponível', especialidade: 'Cirúrgico', higienizacao: '09h10', observacao: 'Reservado para retornos da tarde' },
    { box: 'Box 03', ocupante: 'Thor', status: 'Em observação', especialidade: 'Ortopedia', higienizacao: '06h50', observacao: 'Monitorar dreno' },
    { box: 'Box 04', ocupante: 'Livre', status: 'Manutenção', especialidade: 'UTI', higienizacao: '—', observacao: 'Equipamentos em calibração' },
    { box: 'Box 05', ocupante: 'Amora', status: 'Isolamento respiratório', especialidade: 'Infectologia', higienizacao: '08h30', observacao: 'Acesso restrito com EPIs' },
  ],
};
